### ISSUE TITLE
Internationalization / localization

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherNotes#1]
Title says it basically all. In the long run it would be good if FeatherNotes came with internationalization and localization.

**Comment by tsujan** [comment]
Do you mean translation support, as is done done in FeatherPad?

**Comment by pmattern** [comment]
Yes, that's what I have in mind.

**Comment by tsujan** [comment]
I'll surely add it to FeatherNotes but, since I've promised to myself to add an Esperanto translation, I haven't had time for it yet -- there have been lots of work on FeatherPad and Kvantum, and I have plans to "invade" LXQt panel (now that pcmanfm-qt is in a state of hiatus) ;)

**Comment by tsujan** [comment]
Translation support is added (without any translation) among many other changes.
