### ISSUE TITLE
Translation Terms

### ISSUE THREAD

**Issue by smolnp** [tsujan/FeatherNotes#106]
**"FeatherNotes is being translated using Weblate, a web tool designed to ease translating for both developers and translators. If you would like to contribute to translation of FeatherNotes, you need to register on this server."** 
I do not agree. It’s more convenient for me to see what I’m translating. So I will make a minimum of errors and see the mistakes of previous translators already in the interface. You suggest translating through Weblate blindly.
![screen](https://user-images.githubusercontent.com/26217756/75368332-9be3de80-58d2-11ea-8531-db383debffa6.png)

**Comment by smolnp** [comment]
in favor of offline translation, I’ll add from myself. The server shows that FeatherNotes is translated by 94%, but in fact it is translated by less than 30%
![screen](https://user-images.githubusercontent.com/26217756/75369272-342e9300-58d4-11ea-9d7c-ad9bdad85ec2.png)
there simply copied English text into a string for translation:
![screen01](https://user-images.githubusercontent.com/26217756/75369399-6c35d600-58d4-11ea-8ed9-1b09be013eda.png)

**Comment by tsujan** [comment]
You could use any translation tool you're comfortable with and *your work is very appreciated*. Most translators are comfortable with Weblate. But that doesn't make other methods invalid.

Also see the last part of the file `INSTALL`; there's no mention of Weblate there.

**Comment by smolnp** [comment]
Thank you for understanding

**Comment by tsujan** [comment]
You're welcome.
