### ISSUE TITLE
Auto-resize images -- is it possible with QTextEdit?

### ISSUE THREAD

**Issue by tiotrom** [tsujan/FeatherNotes#123]
Would be great if one can scale the images by simple drag and resize. What do you think about this?

**Comment by tsujan** [comment]
I'm afraid it's impossible with `QTextEdit`, which FeatherNotes uses for its rich text, images and tables. A widget other than `QTextEdit` would be a waste of resources for a lightweight app.

**Comment by tiotrom** [comment]
I understand. Thank you!

**Comment by tiotrom** [comment]
I want to suggest something else maybe: make any image as wide as the window itself. This way it will nicely resize itself when users resize their window. Thoughts?

**Comment by tsujan** [comment]
It's a good idea, although I don't know how easy/hard its implementation is. Will think about it. Thanks!

**Comment by shlyakpavel** [comment]
QTextEdit has an HTML layout behind it. Resizing images in HTML sounds possible. What's wrong here?

**Comment by tsujan** [comment]
> What's wrong here?

Nothing. Working on N projects -- N > 10 -- I need to remember what I've done in each one by seeing my code lines ;)

> QTextEdit has an HTML layout behind it.

Yes, without it, a rich text editor wouldn't be possible. Each node starts with `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">`.

An option should be appropriately added to the scale dialog. The width depends on the position of the splitter handle and viewport margins too. Also, the image should not be made bigger that its real size; etc.

**Comment by tsujan** [comment]
OK, I remembered everything by taking a look at the code. The answer is , "No, it isn't possible to auto-resize images in QTextEdit." This is all that Qt's rich text engine supports about HTML: https://doc.qt.io/qt-5/richtext-html-subset.html

Of course, one can make a Qt-based browser (like Falkon) and auto-resize images but we're talking about `QTextEdit`.

**Comment by marcusbritanicus** [comment]
@tsujan Perhaps it's a little too late, but probably it can be done. QTextEdit relies on `loadResource()` to obtain the images. So if you override `loadResource(...)` you should be quite easily be able to resize the image and render it.

https://doc.qt.io/qt-5/qtextedit.html#loadResource
https://doc.qt.io/qt-5/qtextdocument.html#loadResource

**Comment by tsujan** [comment]
@marcusbritanicus, FeatherNotes can already embed, resize and save images. `QTextEdit::loadResource()` wasn't and isn't needed for that.

**Comment by tsujan** [comment]
> ... fit the available space in the preview?

There's no preview; the view is the final result. FeatherNotes is a notes manager, not an HTML editor

@marcusbritanicus
I think everything will become clear for you if you open an empty note, embed a small image in it, save the note and take a look at its file by using a text editor.
