### ISSUE TITLE
Dictionary + Spellchecking

### ISSUE THREAD

**Issue by tiotrom** [tsujan/FeatherNotes#124]
Do you plan to add these functionalities? Could be useful to quickly fix typos at least. Cheers!

**Comment by tsujan** [comment]
Please use FeatherPad for that!

I might add a similar code to FeatherNotes at some point but no promise. Will keep this open until I make a decision.

**Comment by tsujan** [comment]
OK, I got tired of copy-pasting from FeatherNotes to FeatherPad for spellchecking. Will add spellchecking to FeatherNotes whenever I find the time.

Thanks for the suggestion!

**Comment by tiotrom** [comment]
Thank you!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherNotes/commit/aa5768910c2569270309c4de7708f5020047b160

The Hunspell spell checking is added as an option at compile time and can be enabled by `qmake WITH_HUNSPELL=YES`. Please see the file `INSTALL` for its build dependency (although it's straightforward).

The reason why I made it optional was that some systems may not be able to find Hunspell's headers easily.

**Comment by tiotrom** [comment]
Awesome thank you. I look forward to test it!

**Comment by tsujan** [comment]
You're welcome. It's exactly like in FeatherPad.

**Comment by tiotrom** [comment]
Do you plan to push an official release these days to version 0.7.0?

**Comment by tsujan** [comment]
Yes, in 2 weeks or so.

BTW, distro package maintainers may not be aware of this change and so, they might not add `qmake WITH_HUNSPELL=YES`. I have no way of informing them; I guess distro users will need to tell them.

**Comment by tiotrom** [comment]
Since we added this app as our default note taking app in our distro TROMjaro, then I will make sure to inform the AUR maintainers about that and to update it properly for our distro. You should of course make the maintainers aware of the changes in the release notes ;).

**Comment by tsujan** [comment]
Oh, AUR? Sadly, the AUR maintainer of FeatherPad and FeatherNote is inactive. For example, the latest AUR FeatherPad version is 0.11.1-1, while FeatherPad's latest version is 0.14.1 (and 0.14.2 might be released soon). Moreover, FeatherPad supports `cmake` (FeatherNote will soon) and `cmake` is preferable to `qmake`.

It'll be really great if you could revive AUR somehow. Apparently, others haven't succeeded so far.

**Comment by tiotrom** [comment]
This version https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=feathernotes-git pulls the latest from Github so it should be fine. It is what we use. If the maintainer does not keep it updated in regards to cmake/qmake then we will try to take over and maintain the AUR git package. We keep a close eye on it.

**Comment by tiotrom** [comment]
By the way in case you are curious, this is our custom distro https://www.tromjaro.com/ and we listed this app in our app section too https://www.tromjaro.com/feathernotes/ - we also make icons for the custom icon pack we integrated into the OS and created a new one for FeatherNotes to match the icon pack. Feel free to use it if you wish. In any case, we are very happy with this note taking app and we thank you very much for doing it and maintaining it.

**Comment by tsujan** [comment]
> This version https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=feathernotes-git pulls the latest from Github

Yes, but its maintainers haven't been responsive.

> If the maintainer does not keep it updated in regards to cmake/qmake then we will try to take over and maintain the AUR git package.

That would be great :) Then I could directly tell you about probable future changes -- especially FeatherNotes' `cmake` support, when it becomes ready.

**Comment by tsujan** [comment]
> we also make icons for the custom icon pack we integrated into the OS and created a new one for FeatherNotes

Feel free to use/make any FeatherNotes icon you see appropriate for your distro (BTW, I saw a few of them -- beautiful). FeatherNotes doesn't use a hard-coded icon as its app icon but only for its actions (because some of them aren't found in all well-known icon sets) and then, only symbolic icons that don't interfere with widgets styles.
