### ISSUE TITLE
Bulletpoints

### ISSUE THREAD

**Issue by tiotrom** [tsujan/FeatherNotes#125]
Do you plan to add Bulletpoints to the app? In a note application this can be very useful. Thanks!

**Comment by tsujan** [comment]
Bulletpoints are just characters. You could make a node with such characters (or any other characters) and copy-paste them anywhere you want. Examples (you need a standard font to see them correctly):

○ ◦ ● ▪ ▫ ■ □ ✦ ▲ ► ▼ ◄ ♀ ♂ ♠ ♣ ♥ ♦ ♪ ♫...
😊 😀 😁
∫ ∬ ∭ ⨌ ∮ ∯
✂ ✈ ✉ ✌ ☎

I really prefer not to add duplicate functionalities to my apps; in this way, I can keep them lightweight.

**Comment by tiotrom** [comment]
I understand but lists like this:

- item
- item
- item

or

- [ ] checkboxes

or

1. list
2. list

Are very useful

**Comment by tsujan** [comment]
Use `Shift+Enter`: Write `1. something` (with a space after `1.`) and press Shift + Enter; then, the next line will be `2. `. Write `a) something` (with a space after `a)`) and press Shift + Enter; then, the next line will be `b) `.  And so on.

Please read Help!

Check boxes are also characters: ✓ ✔ ✅ ☑ ❎

**Comment by tsujan** [comment]
And please trust the app; I use FeatherNotes and, certainly, I need to write lists ;)

**Comment by tiotrom** [comment]
Ah yes I apologize! It wasn't clear and yes I did not read the manual. But so will others I suppose. Maybe adding a button for these would be very useful. Or, make it default with enter rather than shift-enter. If I write 1. text and I press enter, it should go to 2. - and if I press enter again it breaks the link and becomes normal. Pretty much all word processors work like that from what I've observed.

Cheers!

**Comment by tiotrom** [comment]
> And please trust the app; I use FeatherNotes and, certainly, I need to write lists ;)

For sure! Thanks a lot for it. I really love it! Just trying to send some useful feedback after testing many many note-taking apps.

We have a custom linux distro called TROMjaro.com and we are looking to ship with a  simple, yet feature-rich note-taking app. So far we love yours and we are testing it.

**Comment by tsujan** [comment]
> Or, make it default with enter rather than shift-enter.

Enter and Shift+Enter have two different jobs. The same is true for Tab (hard tab) and Ctrl+Tab (soft tab). On the other hand, search and replacement are 2 different jobs and I never do them with a single widget in my apps; etc.

Most of what people see as "standards" consists of arbitrary rules that are just copied from other programs without thinking. And some of them have been annoying to me. Moreover, why making another program if one is satisfied with the existing ones?

**Comment by tiotrom** [comment]
I understand you. Is just that in my experience with many text editors the defaults are as I explained. Even in Wordpress (the most known website-builder) is the same. So people are probably used to that. Of course is up to you to do what you want with this app, I was just suggesting... ;)

**Comment by tsujan** [comment]
I understand and really appreciate all of your suggestions, whether I agree with them or not; just wanted to explain my reasons for not following other apps in a few cases (not many).

**Comment by tiotrom** [comment]
I understand and thanks for the explanations. I still think your note taking app is better than most that I tried. ;)
