### ISSUE TITLE
Debian ITP

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherNotes#13]
fyi https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904224

**Comment by agaida** [comment]
@tsujan - a kind of initial tag would be helpful

**Comment by tsujan** [comment]
Will release 0.4.5 with a tag today.

**Comment by agaida** [comment]
[2018-11-22 14:00:38] <BTS> feathernotes (NEW) 0.4.5-1 uploaded by Alf Gaida <agaida@siducti...> (Closes: #904224) https://tracker.debian.org/feathernotes

**Comment by tsujan** [comment]
Thanks!

FeatherNotes may have less commits than FeatherPad does but I'm sure it's quite stable because it has been among my startup apps for years and I use it continuously. However, I'll try to focus on it more in my free time.
