### ISSUE TITLE
The most important feature for research is missing, otherwise, FeatherNotes would be perfect (Feature suggestion).

### ISSUE THREAD

**Issue by joejac** [tsujan/FeatherNotes#140]
The most important feature for research is missing, otherwise, FeatherNotes would be perfect.

Hello and thanks for sharing FeatherNotes, I had years looking for a **replacement** for the abandoned _KeepNote_, which is almost perfect for me. (http://keepnote.org/)

Yesterday I found **FeatherNotes** and I love it, is simple, easy to use, with **friendly formatting**, not the horrible markdown, but is lacking one vital feature, the capability to make **screen captures (screenshots)** from the cursor point inside the notes, so if I am **researching** something and I see a video I can capture a section of the video or the entire frame of the video, If I am reading a PDF paper or a web page, I can capture a full or a partial image or area of the document, documenting my work, or a software package, and so forth and embed them on any note.

I hope you please _take into consideration_ my suggestion to include a **screenshot feature**, perhaps you can use a plugin or some external script that can incorporate into your nice software, please let me know if you _agree_ with this feature, it takes too much time to take a screenshot with an external program, to save it to disk and then import it into FeatherNotes.

Thank you and best regards
Jose

**Comment by shlyakpavel** [comment]
I am not the maintainer of the project, but in my opinion this feature requests violates unix way concept: `Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".`To fulfill your needs, make a global shortcut for screenshot tool that saves the screen or part of it to clipboard and then just paste it into the note. That's simple and fast. As far as I remember spectacle suits exactly what you need.

**Comment by shlyakpavel** [comment]
If I were you, I would not claim that some feature if the `most important`. Everyone has its own needs and these, being combined altogether, make a monster rather than an app.

**Comment by tsujan** [comment]
I completely agree with @shlyakpavel.

Even if I wanted to violate the Unix philosophy — which I don't — and cluttered the code badly, there would be a complication: FeatherNotes works under Wayland as far as Wayland supports its properties (it doesn't support window positioning and focusing); a general screenshot code is impossible for Wayland.

Taking screenshots doesn't have any real use with a notes manager. However, if you want to do it, you could export notes to PDF or HTML and take a screenshot with a PDF viewer or browser.

**Comment by joejac** [comment]
> I completely agree with @shlyakpavel.
> 
> Even if I wanted to violate the Unix philosophy — which I don't — and cluttered the code badly, there would be a complication: FeatherNotes works under Wayland as far as Wayland supports its properties (it doesn't support window positioning and focusing); a general screenshot code is impossible for Wayland.
> 
> Taking screenshots doesn't have any real use with a notes manager. However, if you want to do it, you could export notes to PDF or HTML and take a screenshot with a PDF viewer or browser.

I understand Mr. Tsujan, sorry, I am not a programmer, I am only a user, thus, I do not know how complicated is to implement something, nor I knew **Linux** concept/philosophy, I do not use Unix, I use MX Linux. So KeepNote is violating that Unix 
concept/philosophy.

My apologies for my suggestion and for my ignorance on such matters, I am only a simple user.
Thank you and regards

**Comment by shlyakpavel** [comment]
@joejac thank your for understanding. That is really rare these days and we highly appreciate it. Have a nice day!
