### ISSUE TITLE
features request: bullet + hyperlink

### ISSUE THREAD

**Issue by Cherkah** [tsujan/FeatherNotes#156]
following the request Bulletpoints #125 .
Some features for the editing mode are missing like:

1) bullet (automatic) & list
        [list][*]text[/list]

2) hyperlink:
        [url][/url] or [url=http-link] text [/url]

Those features are really necessary for basic typographic note taking.

3) EXTRA: possibility to change the whole background color for a note.

Feathernotes is an amazing app and it is the only one which fit my expectations on plasma KDE: simple, stable ...

**Comment by tsujan** [comment]
> bullet (automatic) & list

Bullets are UTF-8 characters not different from others (●, ◻, ☑,...). Have a collection of them in a node (search Internet for them) and use them freely with Shift+Enter, which does more than that. See Help and try Shift+Enter after strings like  `1. ...`, `a) ...`, etc.

> hyperlink

Supported since day one. Again see help.

> EXTRA: possibility to change the whole background color for a note.

Already supported.

It seems to me that you may have a very old version of FeatherNotes.

**Comment by Cherkah** [comment]
yes, my version is 0.7.0-3 :/

i will ask the packager if he can update the arch package.

**Comment by tsujan** [comment]
0.7.0 has all the above capabilities except for background colors. It isn't very old.

I wonder how you missed "Insert Link" when right clicking a selected text. FeaterNotes is more advanced than its compact look. It supports both local and external links.

Play with it and you'll find its capabilities.

**Comment by Cherkah** [comment]
sorry you'r right, my bad): the insert link is there.

> Play with it and you'll find its capabilities.
yeah maybe i should play around with it more and do not focus myself only on the toolbar

**Comment by tsujan** [comment]
Only the most important things are on the toolbar. I don't like cluttered GUIs. Most of FeatherNotes' capabilities are spread among its GUI elements, so that its general look is uncluttered. Some others (like Shift+Enter) can't be found in the GUI; hence adding a help doc.
