### ISSUE TITLE
Suggestion: add an option in Preferences to reopen last active note if a file is loaded

### ISSUE THREAD

**Issue by tmsg-gh** [tsujan/FeatherNotes#161]
Title says it all... I have a complex note structure and very often I want to go to the last note that was open (or near that note)... not easy with many notes.

Also, great program... small and does the job very well!

**Comment by tsujan** [comment]
Thanks for caring about FeatherNotes but the feature is already implemented: https://github.com/tsujan/FeatherNotes/releases/tag/V0.8.0

**Comment by tsujan** [comment]
BTW, a "Recently Opened" menu is in my TODO list. I may implement it before releasing 0.9.0.

**Comment by tmsg-gh** [comment]
Hm... I haven't so far tested 0.8.0 (I am still on 0.7.0) but I have looked at the changes before opening the issue and the only thing I've seen was reopening the last file... that's not what I mean (I always give the filename on the command line anyway). However, if this feature also reopens the last opened note than that's what I want (and this should be mentioned in the changelog as well).

**Comment by tsujan** [comment]
See here: https://github.com/tsujan/FeatherNotes/commit/37b0e38167c944e58570160a720935da8cb0fb35

The number of recently opened files can be changed by the user, from 0 to 20 (with 10 as the default). I may add an extra feature to it (opening them inside or outside the current instance).

I should release 0.9.0 soon because important fixes have also been made.

**Comment by tmsg-gh** [comment]
I have a strong suspicion that we're not at all talking about the same thing here. I copy the following lines from #163, noting that this is exactly the same request as mine. If people take the trouble to open an issue with a suggestion, it would only seem polite to actually read AND understand it. IMO.

>  1° request: the option "start with the last opened node" should have to be in your todo-list

That's an acceptable feature request. I'll think about it and might open a page for it after closing this.

**Comment by tsujan** [comment]
> it would only seem polite to actually read AND understand it

Some people may irresponsibly expect telepathy from me. I don't have time for mind-reading or interpretation. This is a bug tracker of a computer program, not a philosophical forum. The reports need to be as specific as possible.

**Comment by tmsg-gh** [comment]
Telepathy, good grief. This is the title (yes, the TITLE) of this issue:

> Suggestion: add an option in Preferences to reopen last active note if a file is loaded

I don't think understanding this simply sentence needs any telepathy at all. You simply misunderstood my request which in itself is NBD, these things do happen.

However, if there's one thing I can't stand it's people who can't admit they were wrong and instead start talking about philosophy.

You are perhaps a good programmer and I will, for the time being, continue to use your program but I will never ever again contact you as your behaviour has been downright ridiculous.

**Comment by tsujan** [comment]
> I don't think understanding this simply sentence needs any telepathy at all

Reading others' comments apart, you should be able to read yours at least. "Note" and "node" are totally difference concepts -- hence mentioning telepathy.

> I can't stand it's people who can't admit they were wrong

I can, apparently.

**Comment by tmsg-gh** [comment]
Is this that hard? FeatherNOTE takes NOTES, eh? You are deliberately obtuse.

And anyway, there are at least two existing issues (#126 #140) where "Note" is used... so it shouldn't have required too much telepathy to figure out what I was talking about.

I will post a few reviews here and there about your willingness to listen to users.

**Comment by tmsg-gh** [comment]
AFAIC EOT.

**Comment by tsujan** [comment]
> You are deliberately obtuse.

Ironically, according to yourself, you're among those people you "can't stand".

> And anyway, there are at least two existing issues

?!

OK, I lock this because the nonsense has gone too far.
