### ISSUE TITLE
Builtin unicode char table

### ISSUE THREAD

**Issue by data-man** [tsujan/FeatherNotes#166]
Sometimes I use [FocusWriter](https://github.com/gottcode/focuswriter) (GPL-3.0 License).
Since 1.4.0 version FocusWriter has Symbols dialog (currently with Unicode 13 data):

![focus_writer_symbols](https://user-images.githubusercontent.com/1754269/106580050-5c3d6200-6539-11eb-8770-135f13da00e2.png)

Small inconvenience: there is no font selection like KCharSelect:

![kcharselect](https://user-images.githubusercontent.com/1754269/106580352-b76f5480-6539-11eb-8ac1-3edd4dcd2209.png)

But KCharSelect has outdated Unicode data. :(

It would be nice to have such feature in the FeatherNotes.

**Comment by data-man** [comment]
cc @gottcode

**Comment by tsujan** [comment]
I'm afraid that's not FeatherNotes' job. Doing the job of another app is a bad practice and against UNIX philosophy ("Make each program do one thing well...").

**Comment by tsujan** [comment]
Related indirectly:

The user can gather special characters in special nodes. For example, I've included several math characters in a node and some emojis in another. *That's* what FeatherNotes is made for, not doing the job of character selector apps.

**Comment by data-man** [comment]
@tsujan 

What other char-table app for KDE would you recommend?

**Comment by tsujan** [comment]
I haven't found a better one.

I copied all special characters that I've put into nodes — and there are many of them — from the Internet, not from char selector apps. Dejavu Sans shows most of them correctly; for the rest — especially, for colored emojis — I've made `~/.config/fontconfig/conf.d/0-emoji.conf` as:

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <!-- For colored emojis: -->
 <match target="pattern">
  <test name="family">
   <string>monospace</string>
  </test>
  <edit mode="append" name="family">
   <string>Noto Color Emoji</string>
  </edit>
 </match>
 <match target="pattern">
  <test name="family">
   <string>serif</string>
  </test>
  <edit mode="append" name="family">
   <string>Noto Color Emoji</string>
  </edit>
 </match>
 <match target="pattern">
  <test name="family">
   <string>sans-serif</string>
  </test>
  <edit mode="append" name="family">
   <string>Noto Color Emoji</string>
  </edit>
 </match>
</fontconfig>

```
Of course, Noto is needed but, in this way, all Qt apps show colored emojis correctly (Konsole, for example).

**Comment by data-man** [comment]
@tsujan 
Thanks!

`kwidgetsaddons` has `kcharselect-generate-datafile.py` tool.
I tried to regenerate `kcharselect-data` (landed in `/usr/share/kf5/kcharselect/kcharselect-data`) by this tool, but it's impossible without changing the file format and the internal API.
