### ISSUE TITLE
FeatherNotes Flatpak?

### ISSUE THREAD

**Issue by fastrizwaan** [tsujan/FeatherNotes#171]
Could we make a flatpak, so that Feather notes is available to more than 30 distributions and their derivatives?

Here's a flatpak manifest, which can be used
```
# io.github.FeatherNotes.yml

# Build
# sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
# sudo flatpak install sudo flatpak install org.kde.Sdk/x86_64/5.15
# flatpak-builder --force-clean build-dir io.github.FeatherNotes.yml
# flatpak-builder --install --user --force-clean build-dir io.github.FeatherNotes.yml

# Run
# flatpak run io.github.FeatherNotes

app-id: io.github.FeatherNotes
runtime: org.kde.Platform
sdk: org.kde.Sdk
runtime-version: '5.15'
command: feathernotes
rename-desktop-file: feathernotes.desktop
rename-icon: feathernotes
finish-args:
- "--share=ipc"
- "--socket=fallback-x11"
- "--socket=wayland"
- "--filesystem=home"

modules:
- name: FeatherNotes
  buildsystem: qmake
  sources:
  - type: archive
    url: https://github.com/tsujan/FeatherNotes/releases/download/V0.8.0/FeatherNotes-0.8.0.tar.xz
    sha256: 9b9a85ce82e67001c5e7b575f09ad4a4d2c14501d79532c902d8d10d7043fc41

```

**Comment by shlyakpavel** [comment]
Of course you can make a flatpak if you like to. The code is licensed under GPL3 that allows that. I don't quite understand what you ask here for.

**Comment by fastrizwaan** [comment]
Feather Notes is a good application. Flathub is a place where apps are packaged as flatpak just like appimage, which can be run on any Linux Distribution (binary distribution). Please visit: https://flathub.org/apps

### About Flathub
Flathub aims to be the place to get and **_distribute apps for Linux_**. It is **_powered by Flatpak_** which allows Flathub apps to run on almost any Linux distribution.

If you are a Linux user, you can use Flathub to gain access to a growing collection of Flatpak applications. You just need to follow the setup instructions.

Submitting apps
App developers can submit their applications to be distributed to Flathub's growing user base, thus providing a single gateway to the entire Linux desktop ecosystem.

At the moment, applications must either be legally redistributable or be available as a third party download. However, if you are a proprietary app developer and are interested in using Flathub, we would love to talk to you.

Get involved
Flathub is an attempt to transform the Linux desktop ecosystem for the better, and we need your help. If you can write documentation, create websites, administer servers or write code, we would love your help.


https://flathub.org/about

**Comment by shlyakpavel** [comment]
Okay
Is there any problem for a developer like you to submit FeatherNotes there just like any distro maintainer submits it?

**Comment by tsujan** [comment]
FeatherNotes is developed here, not packaged. Packaging is a downstream job.

Moreover, I can't recommend methods like "Flatpak". Contrary to what may be advertised, with things like Flatpak, breakage of functionalities is inevitable (I've received and closed reports about them). The best packages are and will always be what distros provide.

**Comment by fastrizwaan** [comment]
Hi @tsujan, 
Please don't take my request otherwise, I just want your software more userbase, and if you look at this https://repology.org/project/feathernotes/versions only very few distributions package FeatherNotes. 

I came to know about FeatherNotes in Debian recentl when I switched to debian, before that I used to use Fedora, never came to know about FeatherNotes, did not find in their software store.

flatpak allows apps to be discovered. and 28 most popular Distros support it. https://flatpak.org/setup/

Packaging for Flathub needs 2 files one is metadata.xml and flatpak manifest (which I have pasted in 1st comment). It won't take much time. 

Just want to thank you for Feather Notes, it is a good software, which I believe should be accessible to more users.

**Comment by tsujan** [comment]
@fastrizwaan 
Thanks for caring about FeatherNotes! I appreciate that.

> only very few distributions package FeatherNotes.

Let me explain it with more details here.

By "what distros provide", I didn't mean specific packages but the *packaging method* itself. For example, under Debian, the best packages are always *deb packages*, whether they are provided by Debian or made by the user himself/herself. Any *other kind* of package can create problems under a Debian system.

That's why I close an unreproducible report as soon as I know that Flatpak or a similar tool is used. I have no problem with Flatpak or its goals but, unfortunately, it makes users believer that Flatpak issues are apps' issues. That's very bad and I really have no time for it — I don't think other devs can have time for it either.

Please also note that what I told above isn't just a theoretical consideration. I encountered it in practice.
