### ISSUE TITLE
Error, when compiling last version 0.9

### ISSUE THREAD

**Issue by mseliger** [tsujan/FeatherNotes#181]
I've compiled the last version with qmake && make.
There was the following error:
```
fn.cpp: In member function ‘void FeatherNotes::FN::textFontDialog()’:
fn.cpp:2907:22: error: ‘class QFont’ has no member named ‘setFamilies’; did you mean ‘setFamily’?
 2907 |         defaultFont_.setFamilies (newFont.families()); // to override the existing font families
      |                      ^~~~~~~~~~~
      |                      setFamily
fn.cpp:2907:43: error: ‘class QFont’ has no member named ‘families’; did you mean ‘family’?
 2907 |         defaultFont_.setFamilies (newFont.families()); // to override the existing font families
      |                                           ^~~~~~~~
      |                                           family
make[1]: *** [Makefile:838: fn.o] Error 1
```
I changed the line in the file fn.cpp
` defaultFont_.setFamilies (newFont.families()); // to override the existing font families`
with
` defaultFont_.setFamily (newFont.family()); // to override the existing font families`
and it works now.

(on Lubuntu 20.04)

**Comment by tsujan** [comment]
`QFont::setFamilies()` is needed by the code — without it, font setting would have problem — but it's in Qt ≥ 5.13.

I'll check whether `QFont::setFamily()` doesn't create bugs. If it does, I should increase the minimum required Qt version to 5.13.

Thanks for the report!
