### ISSUE TITLE
Hunspell included incorrectly

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#219]
https://github.com/tsujan/FeatherNotes/blob/0bfbbd0c9f7ae5453158d59f6bf03134018f5636/feathernotes/spellChecker.cpp#L25
The same problem as fixed by https://github.com/tsujan/FeatherPad/pull/590
Writing this issue not to forget to fix it in the future

**Comment by tsujan** [comment]
Yes, it's good to have an open issue for it. Will make the same changes you made to FeatherPad.
