### ISSUE TITLE
Add an "Insert" menu

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherNotes#22]
![](https://i.imgur.com/Y5xjV7A.png)
i guess this might be a good idea.  
Top text: featherpad
below: the same text (with some additional formats and links) zim-wiki

**Comment by agaida** [comment]
i have just copied over the text from zim to feathernotes, only formatted the headlines
![](https://i.imgur.com/CmRv11x.png)

**Comment by tsujan** [comment]
What happens if you paste with `Ctrl+Shift+V` (not `Ctr+V`)? (see the right click menu!)

See what happens when I use `Ctrl+Shift+V` for pasting the upper contents of this page into FeatherNotes:

![screengrab-20180818-153010](https://user-images.githubusercontent.com/981076/44298625-aeec1a80-a2fb-11e8-8cf9-d9c0d61e9aed.png)

If Zim follows HTML correctly, the contents should be the same (more or less -- tab lengths might be different).

**Comment by tsujan** [comment]
And from your first screenshot, it seems that Zim doesn't use HTML. FeatherNotes formats texts based on HTML, which is the best choice, IMO.

**Comment by agaida** [comment]
Html is just fine - Ctrl+Shift-V does the trick with taking over the formats and links - also fine. My point is only about some pre-defined styles ( I really hate inline styles with all my heart)
``` html
&lt;p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">&lt;a href="https://github.com/tsujan/Kvantum">&lt;span style=" text-decoration: underline; color:#0000ff;">kvantum&lt;/span>&lt;/a> &lt;a href="https://github.com/tsujan/Kvantum/pulls">&lt;span style=" text-decoration: underline; color:#0000ff;">PR&lt;/span>&lt;/a> V0.10.8~36-g3661d95 
```
The ham/spam-ratio is bad - and style changes are nearly impossible too, best example might be:
```
lt;p style=" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">&lt;span style=" font-size:x-large; font-weight:600;">NEW&lt;/span> &lt;/p>
---
<h1>NEW</h1>
```

**Comment by tsujan** [comment]
By default, there's no margin at all (but might be added later, although I think it has no use in a notes manager because text tab/tables/indentation can be used instead). Save a FeatherNotes doc with just an `A` in it and you'll see something like this if you open if with FeatherPad:
```html
<?xml version='1.0' encoding='utf-8'?>
<feathernotes nodefont="Monospace,8,-1,5,50,0,0,0,0,0" txtfont="Monospace,8,-1,5,50,0,0,0,0,0">
 <node name="New Node">&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
&lt;html>&lt;head>&lt;meta name="qrichtext" content="1" />&lt;style type="text/css">
p, li { white-space: pre-wrap; }
&lt;/style>&lt;/head>&lt;body style=" font-family:'Monospace'; font-size:8pt; font-weight:400; font-style:normal;">
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">A&lt;/p>&lt;/body>&lt;/html></node>
</feathernotes>
```

Margins may be created only when you paste a text as HTML and then, they'll be just *inherited*, not created.

**Comment by agaida** [comment]
ok - any way to clean this up?

second question - why &lt; and >

**Comment by tsujan** [comment]
> ok - any way to clean this up?

Could you be more specific? If you mean what's saved in an `fnx` doc, it's standard HTML and the user doesn't need to worry about it -- as he doesn't worry about the real text of an HTML page (in contrast to its visible text + images).

> second question - why &lt; and >

That's what Qt does -- not me ;) See here and the comment below it: https://github.com/tsujan/FeatherNotes/issues/5#issuecomment-289588093

**Comment by agaida** [comment]
ok - `&lt` solved, was just curious about

Self containing is fine - but i would prefer if it would be possible to load a default style with all my preferred settings. (Aka i want my headers green, h1 underlined and so on - and that for all my notes)

**Comment by agaida** [comment]
Re: Processing - i'm a really bad boy, fpad foo.fnx ...

**Comment by tsujan** [comment]
> but i would prefer if it would be possible to load a default style

A piece of cake: Save a styled `fnx` of your choice or, preferably, do it in a node named "Style" or..., and use the mighty `Ctrl+Shift+V`. That's much more flexible than a hard-coded default style. HTML is about free formatting: text, image, table... You could have various styles for various things.

> Re: Processing - i'm a really bad boy, fpad foo.fnx ...

I'd call it curiosity ;) And it could be good for me.

**Comment by tsujan** [comment]
And don't forget to add a good icon to the "Style" node! The more features you use, the more probably I'll get a bug report from you. But FN doesn't have any bug; does it? -- a big lie ;)

**Comment by agaida** [comment]
A style node is a good idea - and would be become even better if the style node could be hidden - and of course populated with some default styles :)

Next thing - why only H1..H3, H1...H5/H6 would be better - i often need at least H5

**Comment by agaida** [comment]
btw - it is not only whining and nitpicking - i really plan to change away from zim-wiki to feathernotes. But i use zim for 7 years now and i'm used to it. One of the very nice features of zim is that it use some kind of markdown. The not so nice thing is that it used a wild markdown mix -- never looked into the code, looks like a creole derivatie.

**Comment by tsujan** [comment]
H1...H5/H6 are a good idea; I'll add them. I'm still against hard-coded styles though.

As for Zim, I'll try it to see what you say.

I've decided not to add any programming language to FeatherNotes -- they're for FeatherPad. I use FeatherNotes for notes managing. The existent notes managers didn't have what I needed (or had what I didn't need). I wanted something for any kind of note: from programming/development notes to personal thoughts, local or remote bookmarks,... -- and even an app that could serve as a dream journal.

However, if you use it more often, you might make it more feature-rich with your reports -- as you did with FeatherPad.

**Comment by tsujan** [comment]
OK, what I might add after seeing Zim:

Inserting date and time (like in FeatherPad), checkbox list and numbered list. Bullet list isn't needed because `Shift+Enter` exists.

Special characters can be gathered from the Internet and put inside a Note (as I've done) but it might be a good idea to add them to a dialog.

In other ways, FeatherNotes is superior to Zim, IMO.

**Comment by agaida** [comment]
erm  - not really yet - one should have a look at the available plugins, the vcs integration etc :D

**Comment by tsujan** [comment]
> erm - not really yet - one should have a look at the available plugins, the vcs integration etc

Because it isn't a notes manager: "A WYSIWYG text editor that aims at bringing the concept of a wiki to the desktop" (Arch's description).
