### ISSUE TITLE
Remember tree collapsed state

### ISSUE THREAD

**Issue by nanoitch** [tsujan/FeatherNotes#242]
I have only just discovered FeatherNotes and I love it.

I have one request. Could FeatherNotes remember the collapsed state when restarting?
At present, every time I launch or restart FeatherNotes, the tree is always expanded.
Even if I save while in the collapsed state, it will open expanded when restarted.
I much prefer it to be in its collapsed state on launch.

Thanks for a great application.

**Comment by tsujan** [comment]
Yes, it's a good idea to add an option for remembering the expanded/collapsed states of all nodes. I'm not sure how easy or complicated it may be. I vaguely remember that I started to implement it but encountered a problem in Qt. Now, being busy with several projects. I rarely find enough time to attack the problem.

However, I'll keep your report open, as a reminder. Thanks for the suggestion!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherNotes/commit/64888f5513ba9d12873a77646f7304da3ee28734 for git users:

![expanded](https://user-images.githubusercontent.com/981076/166211947-37d143c7-bc4e-4689-add6-1a47c398aa6f.png)

If that option is checked (it's unchecked by default), the collapse states of nodes will be among the things that will be saved inside the document and will be applied on opening it.

**Comment by nanoitch** [comment]
Just installed V0.10.1.  The remember expand/collapse nodes feature is working great.
Wow! what a quick fix
Thank you so much.
nanoitch.

**Comment by tsujan** [comment]
Thanks for testing! I felt the lack of this feature for a while. Your report made me focus on it.

If there's a problem, I'll find and fix it before the next release.
