### ISSUE TITLE
[Enhancement] some ideas

### ISSUE THREAD

**Issue by ciranus** [tsujan/FeatherNotes#251]
Hello,
Please find below some ideas/proposals for investigation, nice to have / not requests !

★ LTR/RTL icons removed from toolbar to save space (_not often used, to not say never for most users_)
    -> Menu > Format > RTL/LTR icons should be enough

★ 'Insert line' kb shortcut + toolbar icon

   A
   ⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼
   B

★ Code monospace text formatting: custom FG/BG color preference setting + toolbar MS icon

   ![ksnip_20220518-143751](https://user-images.githubusercontent.com/61602511/169040409-a54da579-fea9-47ac-8a3c-3a3128191e2a.jpg)

★ Global search: highlight nodes containing search string as long as the string is not changed or search feature disabled.

Works fine in plasma 5.

**Comment by tsujan** [comment]
> Removing the icons from the toolbar would not remove any feature

Of course, it doesn't; I've written the code ;) Still, it isn't good to treat LRT and RTL differently in the GUI.

> By 'insert line', I mean... draw a line

A line is nothing but successive Unicode characters (not dashes, of course). Also, please read the last paragraphs of this comment.


> It means select some text , and force monospace font + specific FG/BG color for this selection only.

Changing the fg and bg colors is already possible. A separate font isn't (→ Last paragraphs).

> you have to click 50 times to reach the last one.

If the last node (or any other node) is important to the user, he could activate it and continue the search in it. He doesn't need to wait until the search reaches it.

However, *in the case of searching in all nodes*, it'll be useful if the search string is automatically pasted into the search entry when the user changes the active node. I opened https://github.com/tsujan/FeatherNotes/issues/252.

---

To keep FeatherNotes lightweight, I should avoid features that aren't really needed for note taking and include those that are practical.

For example, supporting a separate font for a part of a document is quite possible but not esential, while supporting a separate bg/fg color is important. Or a list of extra Unicode characters could have been added to a dialog for list/line making, but the user can also create a node that contains as many unusual character as he my want (I have one), making a separate dialog quite redundant.

Of course, these things are open to interpretation and I might change my mind at some point. But, for now, I really want to keep FeatherNotes lightweight while feature-rich, as far as possible.
