### ISSUE TITLE
Save on exit

### ISSUE THREAD

**Issue by ciranus** [tsujan/FeatherNotes#253]
It seems that option to automatically save on exit would be welcomed.

**Comment by tsujan** [comment]
Yes, it's a good option for a notes manager. Thanks for the suggestion!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherNotes/commit/ae7b6ef0778cbfea8be5123f3901872920d6c716

If the new option is checked (it's unchecked by default), an opened document will be saved on exiting without prompt. But if no document is opened or the opened document is deleted/renamed, a prompt will still be shown.
