### ISSUE TITLE
Text overlap when renaming node

### ISSUE THREAD

**Issue by Dialga** [tsujan/FeatherNotes#260]
![image](https://user-images.githubusercontent.com/5157928/173234547-b8ef79d9-ce9f-49e0-bfd8-06b5e09a87e2.png)
When renaming a node the text cursor starts at the beginning of the line overlapping the existing name.

**Comment by tsujan** [comment]
Thanks for reporting! I hadn't seen it because it didn't happen with Kvantum widget style (which I use).

It's a side-effect of checking `Preferences → Window → Transparent tree view`.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherNotes/commit/7e1fe2db54f1240b9f1983b96767ec39c442fe56

**Comment by Dialga** [comment]
Thanks for quick fix!
