### ISSUE TITLE
Ubuntu 20.04 needs for qt5-15

### ISSUE THREAD

**Issue by NailGit** [tsujan/FeatherNotes#277]
I tried to compile version 1.0, but it needs for compilation the version gt5-15 but the default version on ubuntu 20.04 is qt5-12. How can I compile it in my case?

**Comment by tsujan** [comment]
> How can I compile it in my case?

I'm afraid it isn't possible; Ubuntu 20.04 is too old for it.

**Comment by NailGit** [comment]
Maybe you can make a binary file?

**Comment by tsujan** [comment]
Making binary files is a downstream (distro) job. Here, the sources are released.

Anyway, no binary can be made out of V1.0.0 for Qt < 5.15. It's for Qt 5.15 and Qt > 6.3. Keeping backward compatibility with old versions of Qt is a time-consuming job beyond my free time.
