### ISSUE TITLE
Add Line Numbering option

### ISSUE THREAD

**Issue by Xeno-Idaltu** [tsujan/FeatherNotes#286]
Line numbering is needed.

**Comment by tsujan** [comment]
If you mean list making, it's already possible with `Shift+Enter` (→ Help → Hidden Keyboard Shortcuts) — it automatically inserts the next number/letter with `1) text `, `1.  text`, `(a) text` etc. — otherwise, FeatherNotes isn't a code editor (FeatherPad is).

**Comment by Xeno-Idaltu** [comment]
I meant to "Show Line Numbers" to know how many lines each note has.

I'm currently on Kubuntu-22.04, FeatherNotes v-0.8.0, and see no option regarding this usage.

**Comment by tsujan** [comment]
It won't be implemented; I said why above.
