### ISSUE TITLE
Enhancement: Allow "Rename" section of each Node to have its own font properties

### ISSUE THREAD

**Issue by Xeno-Idaltu** [tsujan/FeatherNotes#288]
In the "rename" section, we can't have each node have their own font color and style. This is a handy feature to have since we can use Bold/Colorized Font Styles to make things more eye candy.

**Comment by tsujan** [comment]
I'm afraid making each node have its separate font doesn't seem relevant to note taking.

Of course a notes manager may do various things — it can even have different fonts for different paragraphs  — but I include only  those things that are really pertinent to notes taking. Particularly, I try to avoid cluttering the app or its code unnecessarily.
