### ISSUE TITLE
Shortcut for node name search/fitler

### ISSUE THREAD

**Issue by Dialga** [tsujan/FeatherNotes#316]
Currently to search by node name, you'd need to press multiple shortcuts Ctrl+F and Ctrl+Shift+F7. It would be nice to jump straight to node name search by pressing `/` when a current node is in focus. This would be similar to pressing `/` in google search focuses in the search box, same in gmail and likewise here on github.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherNotes/commit/f0174fad9ad1e5a2370022119e068277c42ec4c8. Also added a short explanation to Help → Hidded Keyboard Shortcuts.

Thanks for the idea.
