### ISSUE TITLE
resize image by drag&drop from corner of them 

### ISSUE THREAD

**Issue by sdfsfsfwrt** [tsujan/FeatherNotes#319]
Hello 
an option for resize selected image by drag&drop from corner of them like joplin

**Comment by tsujan** [comment]
Dropped images can already be resized. There's no plan for duplicating functionalities by adding lots of extra codes.

**Comment by sdfsfsfwrt** [comment]
Maybe I couldn't get my point across ; i was should using 'scaling' word instead 'resizing' 

I think this type of scaling can be useful and make this task very fast rather than scaling with opening dialog and give number to scale image 

[![Z7VMX.gif](https://imgtr.ee/images/2023/06/18/Z7VMX.gif)](url)

**Comment by tsujan** [comment]
I'd understood your point, but perhaps my reply wasn't clear enough.

While images can already be resized, this kind of resizing isn't worth the great amount of extra codes it requires, especially with a lightweight notes manager that's supposed to remain lightweight.

The kind of resizing you mentioned is quite valid for apps that don't aim at lightweightness or don't give it a high priority.

**Comment by sdfsfsfwrt** [comment]
ok another option i suggest 
add a button to toolbar to change scaling with fixed ration 10-20...90 & 100
or select image and press e.g ctrl + up/down key for re-scale image 


goodluck
