### ISSUE TITLE
Weblate link in README

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#33]
Hello.
Weblate was added https://github.com/tsujan/FeatherNotes/issues/12 some time ago, but I still do not see a link in readme. Thus, translation service is not easy to find :)

**Comment by tsujan** [comment]
You're right. I was busy with Kvantum and FeatherPad for a while. Now, I want to attack FeatherNotes and fix some bugs I know about; will fix this too.

**Comment by tsujan** [comment]
Added.
