### ISSUE TITLE
Option to remove text background color html code and set custom text color

### ISSUE THREAD

**Issue by Dialga** [tsujan/FeatherNotes#332]
Currently it is not possible to remove the selected text's background color by removing the HTML value, clicking OK on the background color window the background color will stay the same as before.

A second issue is no ability to set the Text color via the color picker, selecting a custom color then OK - the text remains black. You must click one of the basic colors on left then select the color on the right to make it work.
![image](https://github.com/tsujan/FeatherNotes/assets/5157928/0e4323e4-e219-4055-a001-6b346a0039d2)

**Comment by tsujan** [comment]
> Currently it is not possible to remove the selected text's background color by removing the HTML value

The color dialog doesn't remove colors; it adds or replaces them.

All HTML values are removed only when the Clear button is clicked.

> clicking OK on the background color window the background color will stay the same as before.

Clicking OK always sets the displayed color here.

> no ability to set the Text color via the color picker, selecting a custom color then OK

Again, not reproducible here.

If you meant something else, please describe it step by step, like (1)...;  (2)...; (3)...

Also, please make sure you have the latest release (1.1.1).

**Comment by tsujan** [comment]
Perhaps your problem is about how to use the color dialog in general. Your screenshot shows that you picked a green color but set its *value* to zero (the slider at the right). Any color with zero value is black, as is displayed by the color dialog.

**Comment by Dialga** [comment]
> The color dialog doesn't remove colors; it adds or replaces them.
> 
> All HTML values are removed only when the Clear button is clicked.

This is an unfortunate design decision as if someone wanted to simply remove the background color on a block of HTML formatted text, clicking Clear all formats will reset the text to feathernote's default font.

I'll admit the second issue is a user error(mine).

**Comment by tsujan** [comment]
> ... as if someone wanted to simply...

I avoid cluttering of the GUI for special cases — removed text formats can be added quickly in most cases (also, the user can change colors to white/black).
