### ISSUE TITLE
Exporting html files with slashes in the name doesn't work

### ISSUE THREAD

**Issue by Szybet** [tsujan/FeatherNotes#333]
Propably issues with path handling inside the app

**Comment by tsujan** [comment]
In Linux, slash is the path separator and can't be in file names.

**Comment by Szybet** [comment]
Well, a node can have it and you export a node
Can i make a pull request informing about this error in depth ( Exported file cannot have a slash in the file name )?

**Comment by tsujan** [comment]
> Well, a node can have it and you export a node

The file path is editable in the export dialog. The user can change it; there's no reason that the app should do it for him.

**Comment by Szybet** [comment]
Just **inform** what the exact problem is
