### ISSUE TITLE
macOS icon

### ISSUE THREAD

**Issue by ivan-avalos** [tsujan/FeatherNotes#334]
Hey! I took the time to design a macOS icon for FeatherNotes. FeatherNotes works great on macOS, but the lack of icon makes it look awkward on my Launchpad.

[FeatherNotes.icns.zip](https://github.com/tsujan/FeatherNotes/files/12734369/FeatherNotes.icns.zip)

**Comment by ivan-avalos** [comment]
Actually, here's a patch, to make it easier for you.

[0001-Add-macOS-icon.patch](https://github.com/tsujan/FeatherNotes/files/12734640/0001-Add-macOS-icon.patch)

**Comment by tsujan** [comment]
Thanks for the icon! Please make a PR. I don't have macOS and can't add codes for it.

@shlyakpavel ?

**Comment by tsujan** [comment]
To prevent misunderstanding, I explain it:

I made and develop the app for Linux. Contributors have kindly added codes for Unix, Haiku and macOS. Any code related to those OS's needs to be added a by a contributor who uses them and has tested FeatherNotes in them — like you :) Hence requesting a PR.

**Comment by ivan-avalos** [comment]
The patch I sent contains code I did test on a Mac. I prefer patches over PRs to avoid unnecessary forking, but if you do want a PR, I can make one, no issues.

**Comment by tsujan** [comment]
> but if you do want a PR,...

Yes, please make it. git needs PRs (authors, history of changes, search, etc.).

**Comment by ivan-avalos** [comment]
> authors, history of changes, search, etc.

The patch file already contains all of that. If you download the patch and do `git am 0001-Add-macOS-icon.patch`, it will automatically apply the commit along with the metadata embedded in the file.

> git needs PRs

Just FYI, Git itself doesn't require pull requests, it wasn't built around them. Patches are the standard way of contributing to projects, whereas pull requests are the GitHub way, but they aren't mandatory.

**Comment by tsujan** [comment]
Closed by https://github.com/tsujan/FeatherNotes/commit/96904e1a9adedbef1b1551efad8d82a7e80598ca
