### ISSUE TITLE
[REQ] Option to "Also export HTML" in e.g. same directory, when auto-save is on

### ISSUE THREAD

**Issue by Trinity3e** [tsujan/FeatherNotes#348]
Would certainly come useful.

I would also have a question about an option to export the plain text as markdown and how hard would that be to implement by parsing the xml used here?

Best regards.

**Comment by tsujan** [comment]
Apart from the fact that exporting to HTML isn't an inexpensive operation, I see no reason why the app should do anything other than auto-saving when it auto saves. The user can export to HTML or PDF whenever he/she wants to.

Exporting may be done from HTML to other formats, but that's not FeatherNotes' job. FeatherNotes is made to be and remain lightweight. There are notes managers which may do various, extra jobs — even code editing, video embedding, or calendar organizing — but FeatherNotes is focused on simple notes management.
