### ISSUE TITLE
(enhancement request) Import from .rtf, .xml or from .gde ('The Guide' format)

### ISSUE THREAD

**Issue by caganer** [tsujan/FeatherNotes#355]
Enhancement request: add ability to import a document in one or more of the above formats in order to facilitate the transition to e.g. Debian LXQt by MS Windows users; and (longer term) perhaps also to make FeatherNotes cross-platform for Linux/MS Windows.

FeatherNotes is a comprehensively featured but lightweight outliner and in many respects reflects what might be regarded as its MS Windows counterpart, "The Guide" 
https://theguide.sourceforge.net/features.html
"The Guide is a 32-bit native C++ Win32 application (that uses MFC)".

Sadly, despite its ongoing popularity, The Guide has not been maintained since 2008 but despite that it still works under MS Windows up to at least Windows 10. 

Using a separate cmd executable (gdeutil.exe) The Guide's native .gde data file can be converted / exported as .xml. The Guide is also able to export from within the GUI its .gde file content as .rtf or to print to virtual or hardware printers.

If this is of potential wider community interest, it may also be worth developers posting to The Guide's website for support / donations.

**Comment by tsujan** [comment]
This is a valid feature request, but I'm afraid adding codes for converting specific formats to FeatherNotes Document  (`text/feathernotes-fn`) is beyond the scope of FeatherNotes and also beyond my limited time. Even if I had the required time, I would have to keep the code as manageable and clean as possible.

BTW, FeatherNotes Document (.fnx) is already an XML document (although not reported as XML), but XML can be used very differently by different apps.
