### ISSUE TITLE
Settings for the default font sizes of Text and Nodes.

### ISSUE THREAD

**Issue by PacmanTetris** [tsujan/FeatherNotes#36]
This is a feature request: adding settings for the default font sizes of Text and Notes.

**Comment by PacmanTetris** [comment]
The settings of the Document Font and Note Font in the menu are not saved. They seem to be valid only for the current session.

**Comment by tsujan** [comment]
> The settings of the Document Font and Node Font in the menu are not saved. They seem to be valid only for the current session.

Those settings are saved in the FeatherNotes doc, not in the app. In FeatherNotes, font sizes aren't an app property but a doc property.

I will soon add a commit to set the default font size equal to the system font size but, apart from that, each FeatherNotes doc contains its own font size. There are many differences between a text editor and a notes manager; this is just one of them.
