### ISSUE TITLE
bug on *BSD

### ISSUE THREAD

**Issue by fpusersuggest** [tsujan/FeatherNotes#360]
Hello, I think I found a very hateful bug on OpenBSD 7.5 amd64 **Feathernotes version 1.1.0**
I found the same bug on FreeBSD 13.3 and **Feathernotes 1.2.0**
I have autosave enabled (5 or 3 minutes) and save document on close app enabled.

To reproduce the bug follow these steps:

1. you open an existing notes, we call it "HUGE FN DOCUMENT.fnx"
2. you click on the icon to create a new note and you click yes 
3. you write some text in the new note
4. then you go in "option -> preferences -> text" and you enable or disable "substitute some character.." (I translate from italian)
5. you see the red message that you have to restart the app, then you close the option window.
6. you click on the save icon.

The result is that the original "HUGE FN DOCUMENT.fnx" had overwritten by the new note and you lost the previous note.

I suggest to create a backup folder in ~/.config/feathernotes/ and you save a backup version of the note once you close the app. And you keep the last three versions of each note. This because other bugs may be around the corner.

**Comment by tsujan** [comment]
Thanks for reporting.

> and you enable or disable "substitute some character.." (I translate from italian)

I need to know what that option is in English in order to test your steps. If you tell me what it says in Italian, I could find it.

**Comment by tsujan** [comment]
OK, if you mean "Replace some characters while typing", I followed your steps exactly, and nothing bad happened: The file dialog was opened, I entered a name, and the new note was saved with that name. The original note remained intact, as expected.

Are you sure you didn't overwrite the original note by mistake?

**Comment by fpusersuggest** [comment]
Yes, I'm sure, I tried 4 o 5 times. Both freebsd and openbsd.

**Comment by tsujan** [comment]
I also tried several times — even renamed a big note (~ 2MiB) to `HUGE FN DOCUMENT.fnx` to be thorough — but the result was always OK.

A piece of information may be missing; there should be a hidden factor somewhere. If you think something can be very different about *BSD (compared to Linux), please tell me.

Also, please note that the support for any OS other than Linux is done by contributors, not by me (the author). I have only Linux.

**Comment by fpusersuggest** [comment]
I'm investigating.. if I run the app from terminal I get the error:

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-myusername`

**Comment by fpusersuggest** [comment]
I cloned the git repo and I build the app from your original sources and bug still there. 
Also I renamed the fn.conf file and the bug is disappeared. So I paste my conf that seems to make the bug.

```
[text]
autoBracket=true
autoReplace=false
autoSave=5
dateFormat=dd/MM/yy HH:mm
dictionaryPath=
lastNode=0
lastOpenedFile=/tmp/TEST_HUGE_FN_DOC.fnx
noIndent=false
noWrap=false
openLastFile=true
openReccentSeparately=true
recentFiles=
recentFilesNumber=20
rememberExpanded=false
saveOnExit=true

[window]
fullscreen=false
hasTray=false
max=false
minToTray=false
noMenubar=false
noToolbar=false
position=@Point(286 265)
prefSize=@Size(464 422)
size=@Size(698 471)
smallToolbarIcons=true
splitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0Y\0\0\x2:\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
startSize=@Size(700 500)
transparentTree=false

```

I only removed the `recentFiles`

**Comment by tsujan** [comment]
I used your config file and repeated the steps. The same result: no note is overwritten — the original note is still 2MiB, and the new note is 847 bytes.

**Comment by tsujan** [comment]
At last I was able to reproduce it. Something is very wrong. Will investigate it soon.

**Comment by fpusersuggest** [comment]
ok, the problem appear when you enable the option "Start with the last opened file" under option -> file
so that has nothing to do with autosave or save on closing app.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherNotes/commit/eb3244800ad9d9c2fbf956d6dc4b434454fc3f29

I'm really sorry that you lost your note. Will think about making backups under critical circumstances. For now, I should release 1.3.0.

Thank you very much for reporting this nasty bug! In all years that I've used this app, I hadn't encountered such a nasty problem, but bad issues may happen with a small mistake, like the one that's fixed above.

**Comment by tsujan** [comment]
> ... so that has nothing to do with autosave or save on closing app.

Actually, there was no need to change any setting. What triggered the bug was opening the Preferences dialog after switching to a new note but before saving that note, with a special setting which you had.

**Comment by fpusersuggest** [comment]
No problem. Thanks so much for the fix.
