### ISSUE TITLE
Add Markdown Syntax Highlighting

### ISSUE THREAD

**Issue by glenux** [tsujan/FeatherNotes#361]
Hello,

Firstly, thank you for developing and maintaining FeatherNotes, a great lightweight note-taking tool.

I would like to suggest an enhancement for FeatherNotes: adding syntax highlighting for Markdown. This feature would significantly improve the readability of notes written in Markdown format, making it easier to manage and edit them.

### Current Behavior

Currently, FeatherNotes does not provide syntax highlighting for Markdown, which can make it challenging to read and write Markdown notes.

### Proposed Solution

Implement syntax highlighting for Markdown within FeatherNotes. 

### Additional Information

FeatherNotes is developed using C++ with Qt. I would like to point out that Ghostwriter, another editor developed with Qt, successfully implements Markdown rendering and syntax highlighting. Perhaps their approach could provide some inspiration or guidance on how to achieve this in FeatherNotes.

Thank you for considering this feature request. I believe it would be a valuable addition for many users.

Best regards,

**Comment by tsujan** [comment]
Thanks for your interest in this app.

I'm afraid I don't have a plan to add any kind of syntax highlighting to FeatherNotes. I've developed [FeatherPad](https://github.com/tsujan/FeatherPad) for code editing. FeatherNotes is a notes manager, not a code editor.

> Ghostwriter ... successfully implements Markdown rendering and syntax highlighting

→ https://github.com/tsujan/FeatherPad/tree/master/featherpad/highlighter

**Comment by glenux** [comment]
Hello @tsujan 

Thank you for your response.

I understand that FeatherNotes is primarily a notes manager and not a code editor. However, my request for Markdown syntax highlighting is not intended for coding purposes. Instead, it's aimed at improving the readability of notes written in Markdown, which I use extensively for writing books, courses, documentation, and managing knowledge.

Given that FeatherNotes already supports rich text, integrating Markdown rendering or a basic form of syntax highlighting would greatly enhance the user experience for non-coding content as well.

Could you please reconsider reopening this issue? I believe many users would benefit from this feature.

**Comment by tsujan** [comment]
> Given that FeatherNotes already supports rich text, integrating Markdown rendering or a basic form of syntax highlighting would greatly enhance the user experience.

Syntax highlighting doesn't require a rich text editor (FeatherPad is a plain text editor). More importantly, a rich text editor isn't a good choice for that job because it's too slow.

I really prefer to stick to the Unix philosophy of "making each program do **one** thing well". I don't pretend that FeatherNotes does its job without problem (recently I found a nasty bug and fixed it in 1.3.0), but I don't intend to make it do extra jobs — my limited free time and the number of projects I should attend to don't allow that either.

But thanks for taking time and telling me about your opinion!
