### ISSUE TITLE
Add shortcut for selecting node above/below

### ISSUE THREAD

**Issue by sandebert** [tsujan/FeatherNotes#363]
Just as there are commands for _moving_ a node in the node tree, it would be nice to simply _select_ the node above or below, as a way to navigate the tree. (I can see no reason to complicate it with left/right, just a simple above/below would be sufficient to make it easy to navigate using the keyboard.)

(I searched for this in the many shortcuts but could not find it anywhere. I might have missed it, in that case I'd love a pointer what to look for.)

**Comment by tsujan** [comment]
If you press `Ctrl+Escape`, the tree will be focused and you could navigate it by using `Up` and `Down` keys. To return to the text view, press `Escape` again.

Please see Help → Hidden Keyboard Shortcuts.

**Comment by sandebert** [comment]
Nice, that solves my problem - thank you!

In that case I suggest to add, to bottom of shortcut list, something to the effect of "See Help for hidden shortcuts"

**Comment by tsujan** [comment]
> In that case I suggest to add...

Might do it. Thanks!
