### ISSUE TITLE
prevent simultanous edit of same file

### ISSUE THREAD

**Issue by onstrt** [tsujan/FeatherNotes#377]
I also use the "Featherpad" editor. It has a nice feature that if a second instance of the same file is opened, it opens in browse mode with a different color background to alert the user. The same for Feathernotes would be useful.

**Comment by tsujan** [comment]
You probably have a very old version of FeatherNotes. Since 1.0.0, you can't open the same document twice (see https://github.com/tsujan/FeatherNotes/issues/271).

Using the latest version is highly recommended — especially 1.3.0 fixes a regression that happened in 1.0.0.

**Comment by onstrt** [comment]
Yes, I'm using 0.8.

Unforunately I'm having kernal problems with ubuntu preventing me to upgrade to latest.

Thanks for the reply.

Feathernotes support of user bolding, underlining, italitizing, colorizing etc. is much appreicted.

 
 

Sent: Monday, September 30, 2024 at 2:59 PM
