### ISSUE TITLE
Please update README.md to document how notes are stored

### ISSUE THREAD

**Issue by Talkless** [tsujan/FeatherNotes#387]
Debian Sid just lost KJots, a KDE-based note taking application.

It stored it's notes inside "Akonadi" database.

Once Debian Sid migrated to Qt6/KDE6, the KJots, not being updated, lost access to notes, as backend is now incompatible. Now it's removed from repos.

Currenlty I am looking at different note applications as alternatives, and I see that it would be very useful to know how notes in FeatherNotes are stored, how notes could be accessed in "worst case" scenario if application becomes unusable due to some library updates in Debian (or other distr), etc.

Thanks.

**Comment by tsujan** [comment]
FeatherNotes has no hidden or secret place. The user explicitly saves his/her notes to a file of his choice. The file (a subclass  of XML, with the mimetype `text/feathernotes-fnx`) can be opened in any text editor. It's the user's responsibility to have backups of his saved files.

> if application becomes unusable due to some library updates in Debian

In that case, all Qt apps should be unusable in Debian — an imaginary problem that should be fixed as soon as possible ;) FeatherNotes is based only on Qt, as well as Hunspell for its spell checking; nothing else.

So, README already covers everything a user may want to know before using the app.

**Comment by Talkless** [comment]
Thanks for explanation!

>So, README already covers everything a user may want to know before using the app.

Simply having just "FeatherNotes stores notes in custom XML file at location of user choice" or similar would help.
