### ISSUE TITLE
How to resize an image link?

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#42]
Hello.
It it possible to resize an image that is already embedded in the note?

**Comment by tsujan** [comment]
Yes, it is. Select the image like a text (it'll be OK is some text is also selected) and choose "Scale Image(s)" from the context menu.

**Comment by shlyakpavel** [comment]
@tsujan I do not have such item )
<img width="623" alt="image" src="https://user-images.githubusercontent.com/19782228/51084869-1e96f200-1742-11e9-8787-6eca2b6f919b.png">

**Comment by shlyakpavel** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/19782228/51084872-44bc9200-1742-11e9-9d02-42f69f8370e5.png">
I have such item if the image is embedded via menu. I miss it if I paste the image from clipboard

**Comment by tsujan** [comment]
> I have such item if the image is embedded via menu. I miss it if I paste the image from clipboard

Strange! I have it in all cases. Something related to Mac's clipboard?

I'll look into the code after cleaning up the heavy changes I've made offline. If I find something, I'll include it into the changes; if not, we might have a long discussion ;)

P.S. In previous weeks, I was very busy with LXQt, Kvantum and FeatherPad. Those jobs are finished (for now), so I could focus on FeatherNotes soon.

**Comment by shlyakpavel** [comment]
> I'll look into the code after cleaning up the heavy changes I've made offline. If I find something, I'll include it into the changes; if not, we might have a long discussion ;)

I'm ready for debugging and testing :)

**Comment by tsujan** [comment]
Oh, this is only a placeholder with no image. If you drop it inside FeatherPad, you'll see this (the highlighted text):

![fpad](https://user-images.githubusercontent.com/981076/51126245-e1149080-1837-11e9-858b-c95e7e426c0e.png)

Most probably, the image was only a link but its target is removed with saving.

I should see how to support scaling of image links and preserve their target on saving.

Thanks for the attachment!

**Comment by tsujan** [comment]
> I have some bad news for you

Actually, it was good news ;) Because it might result in a new feature.

**Comment by shlyakpavel** [comment]
> Most probably, the image was only a link but its target is removed with saving.

I made a screenshot and pasted it. It is probably a local link to the file system (not sure about the Mac implementation, KDE works different)

> Actually, it was good news ;) Because it might result in a new feature.

Nice to hear :)

**Comment by tsujan** [comment]
> I made a screenshot and pasted it.

Yes! I can also reproduce it (in two ways). The current code doesn't support it; enhancements should be made..

**Comment by tsujan** [comment]
It's fixed in https://github.com/tsujan/FeatherNotes/commit/eea8de642d3da770c5ee5dcf08d85d834d9390b9

Please test on macOS.

**Comment by shlyakpavel** [comment]
@tsujan 
Works fine!
Thanks a lot!

**Comment by tsujan** [comment]
> Works fine!

Glad to hear that! I thought something in macOS file system might be different but, apparently, Qt is really multi-platform :)
