### ISSUE TITLE
Importing a plaintext file into FeatherNotes

### ISSUE THREAD

**Issue by PacmanTetris** [tsujan/FeatherNotes#43]
This is a feature request.
I would like to be able to open and edit a plaintext file in FeatherNotes just by clicking on it.
The .txt extension would be associated with FeatherNotes, so clicking on a .txt file would automatically import its contents into FeatherNotes, in a newly created note.
This functionality would speed up the workflow of so many users.

**Comment by shlyakpavel** [comment]
@PacmanTetris we have FeatherPad to copy-paste text file content. It's unix-way bro :)

**Comment by tsujan** [comment]
@shlyakpavel is right. Please use [FeatherPad](https://github.com/tsujan/FeatherPad) (preferably, its latest git version). FeatherNotes is not a text editor, let alone a plain-text editor.

**Comment by PacmanTetris** [comment]
I get that, but please also consider the case where you want to import a large number of text files into FeatherNotes, it would be really time-consuming.

**Comment by tsujan** [comment]
You've mistaken notes managers for text editors. FeatherNotes only opens an XML derivative called `text/feathernotes-fnx` because the concept of "node" makes sense only in XML. Opening any other kind of text doesn't make sense.
