### ISSUE TITLE
Mac-specific: no search in main menu

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#44]
The problem here is: unlike Featherpad, Feathernotes does not provide menu search.
Featherpad:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/19782228/51126523-731a9a00-1834-11e9-8ed4-f743ba59d11f.png">
Feathernotes:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/19782228/51126601-9ba29400-1834-11e9-98a5-d9bb317fa288.png">
That's what I found on the web: https://stackoverflow.com/a/11946756

**Comment by tsujan** [comment]
That search isn't done by the app but by Mac's DE. How Mac adds it and why it doesn't add it to some Qt menus, I have no idea.

When I found enough time, I'll search the Internet.

**Comment by shlyakpavel** [comment]
> When I find enough time, I'll search the Internet.

Follow my link :) It is the help menu code breaking it...

**Comment by tsujan** [comment]
> Follow my link :)

Sure; but after making a lot of changes to FeatherNotes -- I'm working of them.

**Comment by shlyakpavel** [comment]
@tsujan 
I have an idea. It is probably the translation that causes search to appear on Mac. Translation is not working in FeatherNotes yet. I'll test this later...

**Comment by tsujan** [comment]
> I have an idea. It is probably the translation

It came to my mind too but I'm completely in the dark with macOS ;)

> Translation is not working in FeatherNotes yet. I'll test this later...

Take your time!

**Comment by shlyakpavel** [comment]
@tsujan yes, Mac needs menu to be in system-wide language for the spotlight search to work. Works fine for me now (https://github.com/tsujan/FeatherNotes/pull/46).
