### ISSUE TITLE
Initial "less-than" of HTML tags replaced by entity while "greater-than" at the end isn't

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherNotes#5]
Character "less-than" at the beginning of HTML tags corresponding with text in the right pane is replaced by entity `&lt;` while the closing "greater-than" isn't.

To reproduce filing arbitrary text in the right pane and saving a file is enough. E. g. simply filing "asdf" in a new document yields
```
<?xml version='1.0' encoding='utf-8'?>
<feathernotes nodefont="Monospace,8,-1,5,50,0,0,0,0,0" txtfont="Monospace,8,-1,5,50,0,0,0,0,0">
 <node name="New Node">&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
&lt;html>&lt;head>&lt;meta name="qrichtext" content="1" />&lt;style type="text/css">
p, li { white-space: pre-wrap; }
&lt;/style>&lt;/head>&lt;body style=" font-family:'Monospace'; font-size:8pt; font-weight:400; font-style:normal;">
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">asdf&lt;/p>&lt;/body>&lt;/html></node>
</feathernotes>
```

FeatherNotes seems to rely on the replacement somehow as it won't open files any longer when entity `&lt;` is replaced with character `<` in an editor.
I don't know whether or not replacing those characters by entities is on purpose. But I think it should be consistent, and with regards to readability of the code not replacing but leaving just `<` would of course be better.

5cc8741 on Arch Linux.

**Comment by tsujan** [comment]
> Character "less-than" at the beginning of HTML tags corresponding with text in the right pane is replaced by entity &lt; 

That's how Qt saves the formatted text. It isn't a problem. FeatherNotes saves the file and reads it correctly.

> it won't open files any longer when entity &lt; is replaced with character < in an editor.

That's expected. `&lt;` shouldn't be replaced by anything. And why doing so in the first place? `fnx` documents only belong to FeatherNotes. Yes, you could open them in an text editor but there's no reason to edit them, especially when they're encrypted (by a password).

> But I think it should be consistent...

It should be *self-consistent* and it is so.

If you want an HTML version of a FeatherNotes doc, you could export it into HTML by using the corresponding menu-item.

I don't understand what's the issue here.

**Comment by tsujan** [comment]
After some digging, I found that Qt intentionally replaces most of `<` characters to prevent potential conflicts. It seems that there's no need to change `>` for that purpose. Anyhow, the important thing is saving and opening a rich text doc correctly and Qt does it perfectly. For example, I made the first version of the Qt-based FeatherNotes in Qt4 but all my docs were opened correctly after I ported it to Qt5. That's while I had a hard time to port the old gtk-based FeatherNotes from gtk2 to gtk3; I had to change the format of all docs (yes, it has a long history).

I close this but feel free to continue the discussion if you have doubts. And thanks for paying attention to such minute details!

**Comment by pmattern** [comment]
The problem is the current handling of entities makes the source files horrible to read. This may be of interest just out of curiosity, which made me stumble upon the problem, or to debug, which apparently wasn't necessary so far. Sure enough replacing in an editor can mitigate the problem both times, as the changes can be reverted before opening the file in FeatherNotes again or simply a copy can be used.

That aside replacing an opening `<` with an entity while leaving the closing `>` as-is still seems a bit weird to me. Also, I've always thought entities are only needed when characters with a special meaning in terms of markup languages are meant to be displayed in regular text, which certainly doesn't apply here.

Anyway considering your explanations this doesn't look like something that should be addressed any longer for now.

**Comment by tsujan** [comment]
> That aside replacing an opening < with an entity while leaving the closing > as-is still seems a bit weird to me.

Believe me, I didn't do it :) Qt does it when it saves something called "QDomDocument" (which is the basis of `fnx` doc). Qt devs should have had their reasons for that. If you google for "QDomDocument XML `&lt;`", you'll find examples from Qt doc itself.

Just out of curiosity, why did you want to edit the `fnx` file in a text editor? I ask because the HTML code can be checked instead after exporting to HTML.

**Comment by pmattern** [comment]
> Believe me, I didn't do it :)

I realized this and didn't claim that thing was your invention.

> Just out of curiosity, why did you want to edit the fnx file in a text editor?

Well
> This may be of interest just out of curiosity, which made me stumble upon the problem, [...]

I was simply curious how the source of FeatherNote's documents looks like.

Talking about replacements, the way the end of nodes in the left pane is marked is subject to changes.
E. g. when a child `foo` is appended to some other node, the end is first marked by a single tag `<node name="foo"/>`. When some content of node `foo` is added in the right pane, there are two tags `<node name="foo"> [...] </node>`, and these persist when the text in the right pane is removed.
Again there doesn't seem to be any downside but it seemed a bit odd to me. So I assume this is on purpose?

**Comment by tsujan** [comment]
> This may be of interest just out of curiosity, which made me stumble upon the problem

Oh, I'd read that but thought you might mean some sort of test that I didn't know of. Now I see.

> ... So I assume this is on purpose?

It isn't about something in the code. Again, Qt does it and it's correct. `<node name="foo"/>` is a short version of `<node name="foo"></node>`. You could see such short versions in `.ui` files too (they're created by Qt designer). If you delete the text of a node and save it, most probably you'll see the long version.

BTW, now that I know about your curiosity, this might help:

you could find the following line in `fn.cpp`:
````
QString str = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
````
Qt changes `<!DOCTYPE HTML PUBLIC...` to `&lt;!DOCTYPE HTML PUBLIC` on saving. Saving is done at this line in the same file:
````
model_->domDocument.save (outStream, 1);
````
The number "1" means indent (one space). After that, Qt does the job and, for some reason, changes `<`. I just trust Qt.

**Comment by pmattern** [comment]
> `<node name="foo"/>` is a short version of `<node name="foo"></node>`

Alright. I wasn't aware of that but that explains it all. Thanks.
