### ISSUE TITLE
Automatically open the last notes file

### ISSUE THREAD

**Issue by rohshall** [tsujan/FeatherNotes#7]
Unlike an editor, a notes app is expected to use the same file as the last time for storing notes. But, Feathernotes starts with a blank slate everytime it is opened, which is contrary to the expectation.

**Comment by tsujan** [comment]
Thanks for your interest in FeatherNotes!

> Unlike an editor, a notes app is expected to use the same file as the last time for storing notes

That can be added as an option, with the current behavior as the default.

**Comment by rohshall** [comment]
Apart from this, the app is expected to automatically save notes, which is what makes it different from an editor app. Currently, we need to explicitly select that option.

**Comment by tsujan** [comment]
> Apart from this, the app is expected to automatically save notes

It already has that (auto-save).

I use FeatherNotes a lot; so, I've added features like that to make it more comfortable.

**Comment by tsujan** [comment]
Preferences → Text → Auto-save every ...

BTW, → was one of those characters I told you about elsewhere....

**Comment by plonibarploni** [comment]
> That can be added as an option, with the current behavior as the default.

Has any progress been made on this? I'm very tempted to used this program, but this is something I find very annoying.

(A little OT, but it seems that FeatherNotes shares a lot code from FeatherPad, but many features have been added to the latter which aren't included in the former. Is there any reason for that?)

**Comment by tsujan** [comment]
> Has any progress been made on this?

No, I was/am busy with more important changes to the code. Since clicking a FeatherNotes doc (text/feathernotes-fnx) opens it in FeatherNotes, this feature doesn't have a high priority; it hasn't been important to me in several years that I've used FeatherNotes for various kinds of docs.

> but this is something I find very annoying.

Sorry, I can't do anything about your feelings.

> but many features have been added to the latter which aren't included in the former.

FeatherNotes and FeatherPad are totally different apps and can't share many features with each other.

**Comment by tiotrom** [comment]
I agree that this can be an useful feature to open the last opened note. Thank you for this app!

**Comment by tsujan** [comment]
> Are pull requests welcome?

Yes, of course! Looking forward to your PR.

**Comment by JackLeEmmerdeur** [comment]
Nice. Just got one problem: The feature is, at least of what I tested, working as intended from within QtCreator and writing to the settings file in my home-folder. But if I copy the binary to system-applications, it is crashing when I click the newly added checkbox in the settings-dialog. I'll try to debug this with qDebug() first.

**Comment by tsujan** [comment]
Since you've worked on it, you could make a PR and I'll review it. Then, we'll discuss probable problems and fix them.

Or you could make a PR after finding and removing the bug from your implementation. Whichever you're more comfortable with.

**Comment by JackLeEmmerdeur** [comment]
I've found where it is crashing. It's within a completely innocent [line](https://github.com/JackLeEmmerdeur/FeatherNotes/commit/4a334ef35e438adbd410048ae5635e0839489fd0#r42336708), of course.

**Comment by tsujan** [comment]
You come from Python's world; don't you? :)  Most of the time, there's no need to `this->...` in C++.

> hopefully adhering to your coding style here

Don't worry about my coding style (or `this->...`). I'll add a commit for cleaning up later.

**Comment by JackLeEmmerdeur** [comment]
Yes I python is my goto for everything quick&dirty. I wouldn't grab C++ for that. Indeed I managed to dodge it most of the time. I wrote a big qt-application in python. But I was a PITA to crosscompile and create executables. So now I'm here and I just love GUI development with C++ and Qt. I just learned some stuff with C++11 only possible with e.g. Java before, which finally makes C++ usable for me. There's Rust, but I desperatley wanted GUI and easy crosscompile binaries. It's all a breeze with QtCreator and the phenomenal Qt framework. I wish I did the jump much earlier.

If this rant isn't appropriate here, I'll delete it.

**Comment by JackLeEmmerdeur** [comment]
So do you want a specific comment or title in the pull request?

**Comment by tsujan** [comment]
Feel free to choose any title. The important thing is the code — I might change the coding style, variable names,... later, after merging.

**Comment by JackLeEmmerdeur** [comment]
I found my mistake. Change `bool startWhereLeftOff...` in Line 97 in fn.h to `void startWhereLeftOff...`.

**Comment by tsujan** [comment]
Done as an option in https://github.com/tsujan/FeatherNotes/commit/b008b1648dad246ff623a3e02cba7d8b2d915a71
