### ISSUE TITLE
Provide checkbox/bullets as formatting option on toolbar

### ISSUE THREAD

**Issue by rohshall** [tsujan/FeatherNotes#8]
Bullets/checkboxes are common formatting options for notes, for example, for a to-do list, or for salient points about something. It will be nice to have it available as one of the formatting options on the toolbar.

**Comment by tsujan** [comment]
There are several signs that can be used for that purpose. Since FeatheNotes supports all sorts of characters, IMHO, it's up to the user to add them to a node and copy/paste them when needed. For example, I have a node with many unusual characters, like:

○ ◦ ● ▪ ▫ ■ □ ▲ ► ▼ ◄ ♦ ¶ © ® № 😄 😃 😂 😁 😀 ...

**Comment by rohshall** [comment]
Yes, but it is different from a list. In a numbered, or bullet-pointed
list, when I select that option, the next line automatically becomes
numbered/bulleted. So, I don't have to explicitly enter the next
number/bullet.

**Comment by tsujan** [comment]
That's another feature that I added to FeatherPad: Shift+Enter. I add it to my TODO list for FeatherNotes.

**Comment by tsujan** [comment]
BTW, I really prefer NOT to clutter the menus more than how they are. If `Shift+Enter` does the job, for example, it's preferable to a new menu-item, IMO.

**Comment by tsujan** [comment]
`Shift+Enter` added in https://github.com/tsujan/FeatherNotes/commit/6f0b19cec67ff8cac9ba3359f71c96c41dae7410. Any kind of bullets can be chosen by the user and then, `Shift+Enter` will add it to the next line (with probable spaces).
