### ISSUE TITLE
where is screenshots?

### ISSUE THREAD

**Issue by amitbha** [tsujan/FeatherNotes#9]
That's an important way to understand application 😆

**Comment by tsujan** [comment]
You're right. Although FeatherNotes is much more than what a screenshot could show, I should add some. Actually, I should do more and add localization too.

I'll do so after finishing some work on FeatherPad. Thanks for the suggestion!

**Comment by tsujan** [comment]
Sorry for the long delay -- I was so busy with other projects, especially FeatherPad. For now, one screenshot is added (after many changes to the code). I'll try to publish the first release soon.
