### ISSUE TITLE
about the use of translated documents

### ISSUE THREAD

**Issue by sunyuting83** [tsujan/FeatherNotes#94]
I have finished translating Chinese. So, how do I use it? Please teach me. thanks.

**Comment by tsujan** [comment]
Thank you very much for translating FeatherNotes! I merged the PR right now (see https://github.com/tsujan/FeatherNotes/pull/93). You don't need to do anything. I'll add your github address to the Translators tab of the About dialog.

If you mean how to use the translation on your computer, it'll be used automatically if you compile the latest git source and have a Chinese localization. With other localizations, you could test it with:

```
LANGUAGE=zh_CN feathernotes
```

**Comment by sunyuting83** [comment]
Thank you. it's works for me.
